### ISSUE TITLE
Wire stopped loading since 2-3 days ago

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2321]
Wire get stuck at a blurry picture of my backgroud image,

Running last beta on android.

Samsung S10

Cleared cache and now get stuck on a black screen after the Wire logo

**Comment by nidico** [comment]
Same/Similar here with Wire 3.39.843 on LineageOS 16.0, installed through APK.

Sometimes the contact list is loading, but the app stops before displaying any contact avatars or message counts. Killing hard and restarting Wire does not help.

For the record: This is a client with two configured Wire accounts.

**Comment by Transisto** [comment]
It fixed itself, 

What happened, 
left the beta channel
Has an OS update
Started to only see a black user list
then came back to normal

**Comment by nidico** [comment]
I'm still having the same issue. I did a minor LineageOS update (model FP2) and also deleted cache partition and Dalvik, but the issue persists - I'm still on 3.39.843 (direct APK download).

Unfortunately, I cannot reopen the issue.

**Comment by marcoconti83** [comment]
Issue reopened

**Comment by estUser** [comment]
Kinda same issue. I downloaded Wire and it insta-crashes when trying to open it. This is the only app that does that to me.

Installed things on my phone:
-Nexus 5
-LineageOS 14.1 (official)
-Magisk
-Xposed

**Comment by marcoconti83** [comment]
Would anyone of those having the issue be able to connect the device to the computer and capture some logs with logcat?

**Comment by nidico** [comment]
@marcoconti83 - yes, I can do that, do you have instructions?

**Comment by marcoconti83** [comment]
@nidico great! 

Are you familiar with `adb`? 
You should install the `adb` tool on your computer (more details [here](https://www.xda-developers.com/install-adb-windows-macos-linux/)) and then extract the logs with [logcat](https://developer.android.com/studio/command-line/logcat).

**Comment by nidico** [comment]
adb currently doesn't work for me due to a broken USB connector. But I can run logcat directly on the device through [SimpleSSHD](http://www.galexander.org/software/simplesshd/). Starting wire yields the log when grepping for wire:

```
10-07 16:49:56.355   885  3577 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wire/com.waz.zclient.LaunchActivity bnds=[231,1263][437,1561]} from uid 10019
10-07 16:49:56.403   885  1839 I ActivityManager: Start proc 10011:com.wire/u0a83 for activity com.wire/com.waz.zclient.LaunchActivity
10-07 16:49:56.802 10011 10022 I com.wire: Background concurrent copying GC freed 26141(4MB) AllocSpace objects, 11(1288KB) LOS objects, 51% free, 5MB/11MB, paused 163us total 122.291ms
10-07 16:49:56.989   386  3016 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=AppWindowToken{e190e71 token=Token{a451418 ActivityRecord{8829bfb u0 com.wire/com.waz.zclient.LaunchActivity t1255}}})/@0x18b793a - animation-leash#0
10-07 16:49:56.989   386  3016 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=AppWindowToken{e190e71 token=Token{a451418 ActivityRecord{8829bfb u0 com.wire/com.waz.zclient.LaunchActivity t1255}}})/@0x18b793a - animation-leash#0
10-07 16:49:57.079   885  3414 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.MainActivity} from uid 10083
10-07 16:49:57.564   885  1836 I ActivityManager: Displayed com.wire/com.waz.zclient.MainActivity: +1s201ms
10-07 16:49:58.122 10011 10022 I com.wire: Background concurrent copying GC freed 109381(4MB) AllocSpace objects, 28(2MB) LOS objects, 49% free, 14MB/28MB, paused 2.468ms total 748.322ms
10-07 16:49:58.202   386  3016 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.wire#0
10-07 16:49:58.202   386  3016 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.wire#0
10-07 16:49:58.606 10011 10075 D         : Successfully queried cache dir: /data/user_de/0/com.wire/code_cache
10-07 16:49:58.606 10011 10075 D RenderScript: Setting cache dir: /data/user_de/0/com.wire/code_cache
10-07 16:49:58.611 10011 10022 I com.wire: NativeAlloc concurrent copying GC freed 185201(9MB) AllocSpace objects, 137(2MB) LOS objects, 49% free, 8MB/16MB, paused 1.211ms total 202.813ms
10-07 16:49:59.527 10011 10022 I com.wire: Background concurrent copying GC freed 107991(9MB) AllocSpace objects, 3(160KB) LOS objects, 49% free, 7MB/14MB, paused 200us total 112.646ms
10-07 16:49:59.998 10011 10022 I com.wire: Background concurrent copying GC freed 102535(8MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6MB/13MB, paused 2.996ms total 102.144ms
10-07 16:50:00.511 10011 10022 I com.wire: Background concurrent copying GC freed 84199(7MB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 8MB/16MB, paused 173us total 152.586ms
10-07 16:50:01.094 10011 10022 I com.wire: Background concurrent copying GC freed 118029(10MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7MB/15MB, paused 494us total 148.761ms
10-07 16:50:01.592 10011 10031 I com.wire: Waiting for a blocking GC ProfileSaver
10-07 16:50:01.594 10011 10022 I com.wire: Background concurrent copying GC freed 96673(8MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 7MB/14MB, paused 284us total 122.255ms
10-07 16:50:02.027 10011 10022 I com.wire: Background concurrent copying GC freed 77012(7MB) AllocSpace objects, 12(212KB) LOS objects, 49% free, 8MB/17MB, paused 246us total 145.727ms
```

**Comment by marcoconti83** [comment]
Hi @nidico ,
Thanks for the logs! We will take a look at them

**Comment by Mikaela** [comment]
I think I am having this issue on both of my phones. They don't get past the Wire logo though.

* Nokia 1 (TA-1047) running Android 9 Go Edition. Stock ROM (while everyone else appears to be using LineageOS?), no root and Play Services installed. I instaled Wire from Play Store. Wire 3.40.844
* Samsung Galaxy S 3 (i9305) running Resurrection Remix (Android 7.1.2), rooted and has no Play Services. I may have installed Wire using Aurora Store. Wire 3.40.844

**Comment by Mikaela** [comment]
My adb for the Nokia 1 would be:

```adb
10-13 13:06:24.106   770  4573 I ActivityManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.wire flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10126
10-13 13:06:28.145   770  1807 I ActivityManager: Force stopping com.wire appid=10263 user=0: from pid 6983
10-13 13:06:28.146   770  1807 I ActivityManager: Killing 6467:com.wire/u0a263 (adj 200): stop com.wire
10-13 13:06:28.148   770  1807 W ActivityManager: Scheduling restart of crashed service com.wire/com.waz.services.websocket.WebSocketService in 61869ms
10-13 13:06:28.156   770  1807 I ActivityManager:   Force stopping service ServiceRecord{f3508c4 u0 com.wire/com.waz.services.websocket.WebSocketService}
10-13 13:07:34.514   770  4533 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wire/com.waz.zclient.LaunchActivity bnds=[26,548][87,609]} from uid 10126
10-13 13:07:34.557   770  4533 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:34.613   770  6046 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:34.685   770   787 I ActivityManager: Start proc 8638:com.wire/u0a263 for activity com.wire/com.waz.zclient.LaunchActivity
10-13 13:07:34.835   770  6046 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:34.887   770  6046 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:36.682   770  3461 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.MainActivity} from uid 10263
10-13 13:07:36.690   770  3461 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:36.904   770  2341 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:36.916   770  2341 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:38.734   770  5042 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:38.789   770   780 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:48.218   770  4045 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:50.011   770  2642 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:50.350   770  1671 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:53.143   770  1829 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:07:53.317   770  1150 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:05.599   770  3461 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:21.178   770  4617 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:28.001   770  4617 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:29.714   770  4425 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:29.971   770  4425 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:30.422   770  4425 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:47.832   770  4533 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:08:48.753   770   780 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:02.436   770  1807 I ActivityManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.wire flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10126
10-13 13:09:05.446  6983  6983 D AppInfoDashboard: Stopping package com.wire
10-13 13:09:05.448   770  1206 I ActivityManager: Force stopping com.wire appid=10263 user=0: from pid 6983
10-13 13:09:05.448   770  1206 I ActivityManager: Killing 8638:com.wire/u0a263 (adj 100): stop com.wire
10-13 13:09:05.464   770  1206 W ActivityManager: Scheduling restart of crashed service com.wire/com.evernote.android.job.v21.PlatformJobService in 69606ms
10-13 13:09:05.465   770  1206 W ActivityManager: Scheduling restart of crashed service com.wire/com.waz.services.websocket.WebSocketService in 99597ms
10-13 13:09:05.478   770  1206 I ActivityManager:   Force finishing activity ActivityRecord{6d554c2 u0 com.wire/com.waz.zclient.MainActivity t131}
10-13 13:09:05.495   770  1206 I ActivityManager:   Force stopping service ServiceRecord{a7710da u0 com.wire/com.waz.services.websocket.WebSocketService}
10-13 13:09:05.496   770  1206 I ActivityManager:   Force stopping service ServiceRecord{c1bf8cb u0 com.wire/com.evernote.android.job.v21.PlatformJobService}
10-13 13:09:05.560  6983  6983 D AppActionButtonControl: Sending broadcast to query restart status for com.wire
10-13 13:09:05.741  6983  6983 D AppActionButtonControl: Sending broadcast to query restart status for com.wire
10-13 13:09:06.087  6983  6983 D AppActionButtonControl: Got broadcast response: Restart status for com.wire false
10-13 13:09:06.710  6983  6983 D AppActionButtonControl: Got broadcast response: Restart status for com.wire false
10-13 13:09:09.121 24890 24914 D conversations: deleted file /storage/emulated/0/Android/data/com.wire/cache/general_cache internal=false, database hits=0
10-13 13:09:09.135 24890 24914 D conversations: deleted file /storage/emulated/0/Android/data/com.wire/cache internal=false, database hits=0
10-13 13:09:15.133   770  2339 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wire/com.waz.zclient.LaunchActivity bnds=[26,548][87,609]} from uid 10126
10-13 13:09:15.157   770  2339 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:15.213   770  2339 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:15.317   770   787 I ActivityManager: Start proc 9452:com.wire/u0a263 for activity com.wire/com.waz.zclient.LaunchActivity
10-13 13:09:15.331   770  1807 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:15.366   770   941 I PhoneWindow: isAPPNeedChange pkgName: com.wire needKeep: false
10-13 13:09:15.376  9452  9452 E com.wire: Not starting debugger since process cannot load the jdwp agent.
10-13 13:09:15.477   770  1807 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:15.497   770  1807 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:16.550  9452  9462 I com.wire: Background concurrent copying GC freed 5378(822KB) AllocSpace objects, 5(496KB) LOS objects, 49% free, 8MB/17MB, paused 323us total 411.265ms
10-13 13:09:16.990  9452  9452 D PackageManager: return text:  Wirefor package: com.wire
10-13 13:09:17.075  9452  9452 I PhoneWindow: isAPPNeedChange pkgName: com.wire needKeep: false
10-13 13:09:17.204   770  2336 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:17.271   770  2336 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.MainActivity} from uid 10263
10-13 13:09:17.282   770  2336 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:17.382   770  2339 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:17.393   770  2339 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:18.449  9452  9452 I PhoneWindow: isAPPNeedChange pkgName: com.wire needKeep: false
10-13 13:09:19.167   311   339 E BufferQueueProducer: [com.wire/com.waz.zclient.LaunchActivity#0] disconnect: not connected (req=1)
10-13 13:09:19.354   770   857 I ActivityManager: Displayed com.wire/com.waz.zclient.MainActivity: +1s953ms (total +4s131ms)
10-13 13:09:19.803   770  4260 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:19.938   770   780 D ActivityRecordAppScale: com.wire computeBounds maxAspectRatio: 0.0
10-13 13:09:20.492  9452  9462 I com.wire: Background concurrent copying GC freed 164182(8MB) AllocSpace objects, 84(3MB) LOS objects, 49% free, 14MB/28MB, paused 21.400ms total 2.313s
10-13 13:09:23.217  9452  9462 I com.wire: Background c
```

The last line didn't complete for some reason and I was grepping for `com.wire` as `wire` was having verbose status on wireless network.

I think the top is me force stopping and clearing cache of Wire to get fresh start / logs.

**Comment by alien2003** [comment]
The same on /e/ on Xiaomi Redmi Note 3 Pro.

Blurry image, after I cleared cache - just black screen

**Comment by alien2003** [comment]
How can I save my chat history?

**Comment by marcoconti83** [comment]
Hi all,
thanks for the reports, we found a potential fix that should be released (at least to beta) in a few days.

**Comment by alien2003** [comment]
This heppenned again. Awesome

**Comment by alien2003** [comment]
And this shit haopenned once again. I think after 3 years of using Wire and promoting it among my friends and family Ill uninstall it and switch back to XMPP. Constant issues with mobile version - non-reliable notifications, crashes and his one. Can you please fix core features before adding useless shit like folders

**Comment by nidico** [comment]
FYI this issue still exists on Wire 3.41.848 (I didn't notice the new version as the app still isn't in f-droid, see #233).

With Wire 3.41, the overall appearance has changed and the app now usually get's past the Wire logo and shows the conversation list (without avatars) and I can switch to search, folders (?) and archive, but I cannot do anything within those lists, e.g. open a conversation / search something.

**Comment by nidico** [comment]
@marcoconti83 - please let us know if the concerned users can help. In any case, here's the new (3.41) logcat output grepped by `com.wire`:

```
10-31 16:02:15.792   965  3204 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.wire/com.waz.zclient.LaunchActivity bnds=[231,1263][437,1561]} from uid 10019
10-31 16:02:15.876   965  1942 I ActivityManager: Start proc 13683:com.wire/u0a83 for activity com.wire/com.waz.zclient.LaunchActivity
10-31 16:02:16.444   377  8220 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=AppWindowToken{b75ad4b token=Token{d2bde1a ActivityRecord{7224c5 u0 com.wire/com.waz.zclient.LaunchActivity t1563}}})/@0xcfdaf6c - animation-leash#0
10-31 16:02:16.444   377  8220 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=AppWindowToken{b75ad4b token=Token{d2bde1a ActivityRecord{7224c5 u0 com.wire/com.waz.zclient.LaunchActivity t1563}}})/@0xcfdaf6c - animation-leash#0
10-31 16:02:16.856 13683 13698 I com.wire: Background concurrent copying GC freed 100509(4MB) AllocSpace objects, 26(2MB) LOS objects, 56% free, 4MB/10MB, paused 193us total 123.169ms
10-31 16:02:17.117   965  5084 I ActivityManager: START u0 {cmp=com.wire/com.waz.zclient.MainActivity} from uid 10083
10-31 16:02:17.156   965  1939 I ActivityManager: Displayed com.wire/com.waz.zclient.MainActivity: +1s328ms
10-31 16:02:17.290   377  8220 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.wire#0
10-31 16:02:17.290   377  8220 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.wire#0
10-31 16:02:17.697 13683 13721 W com.wire: Long monitor contention with owner pool-4-thread-1 (13712) at com.waz.service.call.FlowManagerService com.waz.service.GlobalModuleImpl.flowmanager$lzycompute()(GlobalModule.scala:197) waiters=0 in com.waz.service.call.FlowManagerService com.waz.service.GlobalModuleImpl.flowmanager$lzycompute() for 151ms
10-31 16:02:17.832 13683 13692 I chatty  : uid=10083(com.wire) FinalizerDaemon identical 3 lines
10-31 16:02:17.835 13683 13698 I com.wire: Background concurrent copying GC freed 76114(3MB) AllocSpace objects, 12(584KB) LOS objects, 49% free, 8MB/17MB, paused 807us total 345.294ms
10-31 16:02:18.886 13683 13698 I com.wire: Background concurrent copying GC freed 131553(6MB) AllocSpace objects, 133(2MB) LOS objects, 49% free, 9MB/19MB, paused 600us total 254.515ms
10-31 16:02:18.949 13683 13692 I chatty  : uid=10083(com.wire) FinalizerDaemon identical 7 lines
10-31 16:02:19.039 13683 13698 I com.wire: NativeAlloc concurrent copying GC freed 26408(924KB) AllocSpace objects, 1(16KB) LOS objects, 50% free, 9MB/19MB, paused 445us total 149.999ms
10-31 16:02:19.154 13683 13744 D         : Successfully queried cache dir: /data/user_de/0/com.wire/code_cache
10-31 16:02:19.155 13683 13744 D RenderScript: Setting cache dir: /data/user_de/0/com.wire/code_cache
10-31 16:02:20.122 13683 13698 I com.wire: Background concurrent copying GC freed 115687(9MB) AllocSpace objects, 5(200KB) LOS objects, 50% free, 10MB/21MB, paused 516us total 166.709ms
10-31 16:02:20.861 13683 13698 I com.wire: Background concurrent copying GC freed 148735(12MB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 10MB/20MB, paused 444us total 116.088ms
10-31 16:02:22.075 13683 13698 I com.wire: Background concurrent copying GC freed 123600(10MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 11MB/23MB, paused 122us total 140.984ms
```

**Comment by marcoconti83** [comment]
@nidico thanks for asking.
Our best guess at the moment is that there is a deadlock causing some future to never complete. Unfortunately there is no exception in the logs, so we are not sure which future it is. At the current state, the logs won't help. 

We are trying to pin point by going through the code and looking for all the places where this could hang. If anyone in the community has a suggestion on how to make this process faster, we are happy to hear!

**Comment by Transisto** [comment]
@marco my Wire now often stop halfway through the replaying of the past
events. I think you should try loading wire with 70+ messages in different
group that happened from another devices (desktop)

It looks ridiculous to see every conversation move up and down for 1 minute
while all previous received messages affect the threads orders. I often get
confused about whether these are new messages or not.

**Comment by Transisto** [comment]
This is getting so ridiculous, If Wire is supposed to be used for teamworks it should be tested with high number of messages. Currently the whole experience can be summarized as buggy, sluggish, unreliable.  My Wire on android works but has to be force closed half the time I want to use it. I have employee's who's Wire on IOS can't open at all, (crashes just as it starts to open).  My experience on desktop is frankly disgusting, Every actions takes 3-10 seconds to take place.

**Comment by Transisto** [comment]
I created this issue and still have various version of the same problem, It's as if wire stop receiving data or processing them at different stage,  Sometime app just stop updating in the very middle, sometime it loads a few dozen old message then stop with the orange load bar forever spinning, every-time I have to close and reopen the app so it goes a little further, often 2-3 times.
I was just about to try sharing something, I get to the part where I search the users I want to share to, There is nothing there, can't type just an empty search bar.
I close the app, reopen it, It get stuck on the white on black logo.
I close and reopen, not it get suck on my blurred background image.
stuck 4 time the same way
now stuck on logo, now stuck on image, reboting the phone, stuck on logo, then stuck on image.
Gonna leave it a few hours on that image who knows, maybe it'll get going eventually ¯\_(ツ)_/¯
This thing was working fine today then stopped working again randomly, Good thing I have it working on two phones, the other one lost everyone's profile images, maybe that alleviate it's bloat and is what keeps it for stalling.

**Comment by alien2003** [comment]
It fucking happenned again. I fucking hate this shitty unreliable messenger. I hate it because  I'm in another city and don't have access to my computer. WTF? How can I read all messages I lost? I hate this messenger even more because it was good and stable and I convinced all my friends to switch to it. And now I can't just uninstall his peace of crap.

XMPP apps released 10 years ago have all the same features and are stable and reliable

**Comment by alien2003** [comment]
And... again after few hours ![](https://i.imgur.com/n9REE3P.png)

**Comment by marcoconti83** [comment]
Dear all,
we are working hard on addressing these issues, that are extremely hard for us to reproduce reliably and therefore to debug. This is taking more time than we hope, thank you for your patience.

We are trying tentative fixes one by one, then rolling out one by one with experimental builds to internal people that have this issue occasionally, then collect their feedback (e.g. "it did not happen for 2-3 days"). It's a slow process, unfortunately, but because we don't have a way to reproduce this reliably on test devices, it's the only way we can go forward.

Since these are experimental fixes, we don't feel comfortable releasing them to public beta because they might break more things that they fix, until we tested it properly internally.

**If you want to help** and you are able to compile yourself, you can try our latest tentative fix and report if it fixed it for you (by observing the app for a few days): https://github.com/wireapp/wire-android/pull/2417

**Comment by alien2003** [comment]
Consider releasing temporary fixes, at least for Beta users. The app is absolutely non-reliable for month

**Comment by dpsmith** [comment]
@marcoconti83 I appreciate the challenge you all are facing but not having access to Wire on my Android device for over a month is frustrating. I am not sure if it will help, but a data point is that a colleague and I have the exact same phone (Pixel) at the same update level. Wire works fine them while on my phone it can never get past the originally described behavior. The only notable difference is that they only have a couple of contacts and three message groups. Where as I have over 20 contacts and likely close to 50 conversations some of which I get a high volume of messages each day. Unfortunately I do not have the bandwidth to build and test but I would be willing to help test beta releases as having a partially working client would be better than no mobile client at this point.

**Comment by JulianTosh** [comment]
@dpsmith This struck a chord with me. I'm a high volume user too, with lots of contacts, messages, groups, and media links/images. This problem happens to me and resolves itself sometimes on its own if I just let it sit and meditate. The outage can be hours or days (very frustrating). Only once did I delete my account and regenerate keys to get back to a working state on my phone - because it was one of those days outage. Most of my friends I've talked into using Wire don't complain about this problem much, so it seems its related to high volume users.

**Comment by alien2003** [comment]
And once more. Is there a built-in timer that stashes it every day?

**Comment by alien2003** [comment]
Somehow I passed through it and I now can see partially rendered UI. I can only access archive, other tabs are blank. Can't click on any contact, just does not work. Settings OK except my user pictures is not rendered

**Comment by marcoconti83** [comment]
We are still testing https://github.com/wireapp/wire-android/pull/2417 internally and it looks like we could prepare a Beta soon

**Comment by marcoconti83** [comment]
Hi all,
We just released to public **beta** version 3.43.865, which according to our testing addresses the issue at least for some users (but we got reports that other users have a similar issue).

If you could give beta a try, please let us know how it is going!

**Comment by nidico** [comment]
@marcoconti83 : Thanks for the update! Is there any way to install the beta version without google play?

**Comment by Transisto** [comment]
Latest update has shown me all my contacts, some with notification on them,
some notications that should have been cleared more than a week ago, never
been able to tap into a user, spinner kept going, stuck.
Closed and reopened
Could then see my contact then if I scroll down and back up the image
profile disappeared and still nothing can be done.
Closing, rebooting phone,
Now app only show a my blurry background image, nothing more.

**Comment by derkommutator** [comment]
Build 865 has not solved the problem.  Seems the same as 863:  It works fine for a while, then inexplicably starts stalling.  The stall I am currently seeing is at the contact list.  It's showing the whole list, but is not catching up on messages, and is constantly showing the "busy" animation across the top.

Since I am entering this thread a little late, I'll remark that I disagree with the suggestion made earlier that this is happening only to people with many contacts and high volume.  I have 11 contacts and fairly low volume, and have been experiencing this problem for several weeks now.  It is quite aggravating, and I echo the concerns of others that we have convinced many of our friends and family to use Wire, and now the quality of the product has been in steady decline for the past year or so.  It is unfortunate to see a formerly great messenger get mired in feature bloat while bugs continue to arise and render the platform far less useful than it used to be.

**Comment by Transisto** [comment]
That loading bug has lots of similarity and was never solved on my side.

https://github.com/wireapp/wire-android/issues/2003

It's as if when it got stuck on loading it would recover after a restart
but it doesn't do that anymore. With last update I've first witnessed
seeing my contact list receive a few old notification then stopping, then
nothing... At all.

**Comment by Transisto** [comment]
@marcoconti83 

This morning I was stunned to see a wire notification, I opened it and had the whole thing replay the last month of stuck activity, took about 30min but it didn't stop like it would usually do.

I don't know if you've done anything on your servers sides but it fixed it for me,

**Comment by marcoconti83** [comment]
Thanks everyone for the feedback.
It seems that the fix works only sometimes - it makes the situation better for some people, but others get stuck later anyway. We'll keep working on this.

**Comment by Powersource** [comment]
Had this also about a week ago. Not sure what fixed it. Now I have this instead https://github.com/wireapp/wire-android/issues/2431

**Comment by nidico** [comment]
After updating to 3.42.863 (which isn't listed in https://medium.com/wire-news/android-updates/home though) and restarting the device, a notification icon appeared and some 53 days old messages showed up in the notification. Unfortunately trying to start wire still doesn't work - it hangs just as before.

As written above, I cannot test the beta as I don't have google play. If there's another way to install the beta without building the whole thing from source please let me know.

**Comment by marcoconti83** [comment]
Hi all,
We have another fix in the pipeline that seems to resolve the issue for more users, we will push to beta in the next few days.

**Comment by Transisto** [comment]
After not working for a month and coming back for a full week it randomly stopped again, no amount of rebooting the app/phone helps,  Will just wait for another of God's intervention.

**Comment by marcoconti83** [comment]
Hi all,
A new beta version of 3.43.870 has been just published. It would be great if you could update to this beta version to confirm if the issue is fixed for you!

**Comment by marcoconti83** [comment]
Hi all,
This has now been released to public.

**Comment by nidico** [comment]
Version 3.43.870 seems to fix the issues - a lot of messages from the last 60 days from two accounts are being synced right now. This is a very slow process which sometimes stalls for some minutes - some patience is required... Will update the post when it's finally done.

Anyway - thanks to the Wire team for the fix, finally! :)

**Comment by Mikaela** [comment]
It appears to be somewhat working for me also. Nokia 1 is somewhat sluggish and Samsung Galaxy SIII (no Play Services) seemed to have some issues syncing 56 days old notifications.

**Comment by marcoconti83** [comment]
Thanks everyone for the feedback!
We are aware that catching up with weeks of messages takes a long time. This is something we hope it won't be needed again very often :) 
For now, we are interested in knowing if the app is working again and if user are able to receive and send message again.

**Comment by Mikaela** [comment]
I have been sending and receiving messages today (UTC), so I think this is fixed.

**Comment by marcoconti83** [comment]
Thanks everyone for the feedback!

**Comment by derkommutator** [comment]
I know this is already closed, but since I was one of the ones who was having trouble and posted earlier, I'll remark that the problem is also gone for me.  Thanks for the fix!
